INSERT INTO USER (ID, NAME) VALUES (1001, 'Dummy user1');
INSERT INTO USER (ID, NAME) VALUES (1002, 'Dummy user2');
INSERT INTO USER (ID, NAME) VALUES (1003, 'Dummy user3');
INSERT INTO USER (ID, NAME) VALUES (1004, 'Dummy user4');
INSERT INTO USER (ID, NAME) VALUES (1005, 'Dummy user5');